Patch docs
UBC-MDS/diabetes_predictor_py pull request #2
Opened 2024-11-20 06:56 UTC by InderKhera

2024-11-21 02:02 UTC, JennyonOort requested changes
Finally, in the example milestone provide to us (https://github.com/ttimbers/breast-cancer-predictor/blob/0.0.1/notebooks/breast_cancer_predictor_report.ipynb), there is Methods section with Data and Analysis subsection that seems to be part of code narrative. 

Would you mind taking on the Data part since you did the EDA and I can take on writing the Analysis part?

Thanks again for being so prompt with your part and help push progress forward! Do let me know if any questions or concerns with the comments I made.

2024-11-21 02:02 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +    "feature_histograms "
For EDA visualization: would it make sense to visualize as overlapping histogram / density plots so that comparison is easier on the eye and on the same scales

2024-11-21 02:02 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +   "source": []
This is an extra empty code block before data split, should delete

2024-11-21 02:02 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +    "The Graphs above shows us the respective distribution of each of the features. We have faceted the results to show the how distribution of each feature is when the Outcome is 0 (Non-Diabetic) an
For Additional EDA: add pairwise scatterplot comparison and correlation plots (can refer to code from lab1 in 573 using `altair_ally`) as Logistic Regression have a few assumptions and no multcollinearity is one of them. Plotting the pairwise scatterplots and correlation plots can effectively gauge relationships and confirm that data is fit to apply Logit Regression.

2024-11-21 02:02 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +    "We optimze the hyperparamter 'C' for our logistic regression using a random search"
Should we consider adding class_weights? I understand it is materials from 573 but it seem quite important for our case.

2024-11-21 02:02 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +    "                                   n_iter=7,\n",
For RandomizeSearchCV, would recommend n_iter of at least 20 so that a converging and an optimal results can be received. Do let me know if there is a specific reason that we are using n_iter = 7 in the current version that I am missing.

2024-11-21 02:02 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +    "We will be using a Logistic Regression model to do our classification. Since our features have outliers it would be best to use a StandardScaler() to normalize the feature values before fitting
Should add Dummy Regressor as baseline - so we know how well our model performs relatively.

2024-11-21 02:02 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +    "pd.DataFrame(random_search.cv_results_).sort_values(\n",
The randomizedSearchCV results seem a bit low in terms of accuracy, should we consider alternative models or consider other scores such as f1? 

Understand f1 is content from 573 but seems a better indicator given class imbalance. 

If to consider alternative models, we can add a code chunk where we explore different models and pick the one with best cv score, like we did in lab in 571.

2024-11-21 21:29 UTC, InderKhera commented on analysis/diabetes_analysis.ipynb
> +    "pd.DataFrame(random_search.cv_results_).sort_values(\n",
I talked to Tiffany yesterday the main focus is not how well the model performs. She mentioned as a Data Scientist there will be time where we design a model and it does not perform as well as we expect. In the real word we will then need to figure out why it was this way, whether we need a better sample for our model, or different features. 

Also they want us to keep our model based on 571 to make it easier for TAs to mark consistently

2024-11-21 21:31 UTC, InderKhera commented on analysis/diabetes_analysis.ipynb
> +    "We optimze the hyperparamter 'C' for our logistic regression using a random search"
I believe they currently want us to keep it based off of 571 material for now

2024-11-21 21:34 UTC, InderKhera commented on analysis/diabetes_analysis.ipynb
> +    "                                   n_iter=7,\n",
changed to  n_iter = 20

2024-11-21 21:35 UTC, InderKhera commented on analysis/diabetes_analysis.ipynb
> +    "feature_histograms "
added overlapping plots for the features

2024-11-21 21:35 UTC, InderKhera commented on analysis/diabetes_analysis.ipynb
> +    "The Graphs above shows us the respective distribution of each of the features. We have faceted the results to show the how distribution of each feature is when the Outcome is 0 (Non-Diabetic) an
added pairwise scatter plots and correlation plots

2024-11-21 21:37 UTC, InderKhera commented on analysis/diabetes_analysis.ipynb
> +   "source": []
deleted empty code blocks

2024-11-21 21:44 UTC, InderKhera commented on analysis/diabetes_analysis.ipynb
> +    "We will be using a Logistic Regression model to do our classification. Since our features have outliers it would be best to use a StandardScaler() to normalize the feature values before fitting
I believe DummyClassifier would be the correct model for a baseline for a Logistic Regression as we are classifying based on our target 'Outcome'. Dummy Regressor is more for continuous targets

That being said I have added the DummyClassifier model to the analysis as well

2024-11-22 07:26 UTC, JennyonOort commented on analysis/diabetes_analysis.ipynb
> +    "The Graphs above shows us the respective distribution of each of the features. We have faceted the results to show the how distribution of each feature is when the Outcome is 0 (Non-Diabetic) an
Looks good!

2024-11-22 07:28 UTC, JennyonOort approved these changes
Changes all looked good and reflective of the last review. Thanks much for the great collaboration and work! No further comments from my side and approving this pull request.

2024-11-22 16:35 UTC, merged